### PR TITLE
Adding package.json so I can do npm install on this package.

### PR DESCRIPTION
**Pull request by dodozhang21**
Tyler, could you please accept this package.json so I can just pull your repo directly as my dependency? 

Please also create a tag with `1.0.0` - matching the version number in package.json when you accept this PR.

Thanks

### CODE REVIEW

**Comment by tvler** [comment]
Hey!! I'd be happy to :)

**Comment by tvler** [comment]
I'll set this up after work today

**Comment by tvler** [comment]
@dodozhang21 @agarzola are you two interested in consuming this library as an es6 module? Something like:
``` jsx
import loadMedia from 'lazy-progressive-enhancement'
```

... or are you more interested in just having an easier way to install and use this library?

**Comment by dodozhang21** [comment]
Not really. Just using it directly on the client side. Thanks

**Comment by agarzola** [comment]
@tvler Hi! 👋 Found this PR waaaay at the bottom of my global `/pulls/mentioned` and made me wonder what’s holding this up from being merged. Is there anything we can do to improve on this PR and get it into `master`?

**Pull request merged**
